apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: xray-images-anonymized
  labels:
    strimzi.io/cluster: kogito-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
