apiVersion: app.kiegroup.org/v1beta1
kind: KogitoBuild
metadata:
  name: xray-process
spec:
  type: Binary
---
apiVersion: app.kiegroup.org/v1beta1
kind: KogitoRuntime
metadata:
  annotations:
    org.kie.kogito/managed-by: Kogito Operator
    org.kie.kogito/operator-crd: KogitoRuntime
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
  labels:
    app: xray-process
    xrayprocess: process
  name: xray-process
spec:
  serviceLabels:
    app: xray-process
  infra:
    - kogito-kafka-infra
    - kogito-infinispan-infra
  resources:
    requests:
      memory: 1Gi 
    limits:
      memory: 2Gi 
  replicas: 0